# ====== SEOUL256 THEME ======
# Paleta:
#   base03  #151513  crust
#   base02  #30302c  bg
#   base01  #4e4e43  surface
#   base00  #666656  
#   base0   #808070  subtext
#   base1   #949484
#   base2   #a8a897
#   base3   #e8e8d3  fg
#   blue    #87afaf
#   green   #87af87
#   cyan    #87d7d7
#   red     #d68787
#   yellow  #d8af5f
#   magenta #df5f87
#   peach   #d7afaf

# ====== GENERAL ======
set -g mouse on
set -g history-limit 100000
set -g extended-keys on
set -g base-index 1
setw -g pane-base-index 1
set -g escape-time 50
set -g focus-events on
set -g default-terminal "tmux-256color"
setw -g mode-keys vi
set -g renumber-windows on
set -g set-clipboard on

# ====== PREFIJO ======
unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind-key C-a last-window

# ====== SPLITS ======
bind | split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind -n M-v split-window -h -c "#{pane_current_path}"
bind -n M-s split-window -v -c "#{pane_current_path}"

# ====== NAVEGACIÓN ======
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# ====== REDIMENSIONAR ======
bind -n M-H resize-pane -L 5
bind -n M-J resize-pane -D 5
bind -n M-K resize-pane -U 5
bind -n M-L resize-pane -R 5

# ====== WINDOWS ======
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-t new-window -c "#{pane_current_path}"
bind -n M-c new-window -c "#{pane_current_path}"
bind -n M-x kill-pane
bind -n M-Left previous-window
bind -n M-Right next-window
bind -n M-BSpace kill-window

# ====== RECARGAR ======
bind r source-file ~/.config/tmux/tmux.conf \; display "Config recargada"

# ====== STATUS ======
set -g status-position top

# ====== COPY MODE VI ======
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel
bind -T copy-mode-vi Escape send -X cancel

# ====== TMUX-GRUVBOX THEME ======
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark256'
set -g @tmux-gruvbox-left-status-a '#S'

# ====== TPM ======
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'MaximilianGaedig/tmux-filter'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'off'
set -g @continuum-save-interval '15'

run '~/.config/tmux/plugins/tpm/tpm'
